receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128

  resource:
    attributes:
      - key: service.name
        value: simian-forge
        action: upsert

exporters:
  # Export traces to Elasticsearch
  elasticsearch/traces:
    endpoints: ["http://elasticsearch:9200"]
    traces_index: traces-simian-forge
    mapping:
      mode: ecs
    logs_dynamic_index:
      enabled: true

  # Export logs to Elasticsearch
  elasticsearch/logs:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: logs-simian-forge
    mapping:
      mode: ecs
    logs_dynamic_index:
      enabled: true

  # Export metrics to Elasticsearch
  elasticsearch/metrics:
    endpoints: ["http://elasticsearch:9200"]
    metrics_index: metrics-simian-forge
    mapping:
      mode: ecs

  # Debug exporter for troubleshooting
  debug:
    verbosity: basic

  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [elasticsearch/traces, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [elasticsearch/logs, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [elasticsearch/metrics, prometheus, debug]

  extensions: []

  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888